{{- if .Values.extraCAs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-server.fullname" . }}-extra-ca
  namespace: {{ include "spire-server.namespace" . }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
data:
  ca.crt: |
{{ .Values.extraCAs | indent 4 }}
{{- end }}
